<div>
    <section class="text-gray-600 body-font">
        <div class="container px-5 mx-auto">

            <div class="flex flex-col text-center w-full mb-15">
                <h1 class="md:text-4xl text-3xl font-bold title-font text-gray-900">
                    {{ $prompt->header }}
                </h1>
            </div>

            <div class="flex flex-col items-justify-start w-full mb-12">
                <h2 class="md:text-2xl text-xl font-medium text-gray-700 mb-4">
                    {{ $prompt->subHeader }}
                </h2>
                <p class="md:text-xl text-lg font-base mb-5">
                    {{ $prompt->content }}
                </p>
                <p class="text-sm font-normal">
                    Generated by AI using: <span class="font-medium">{{ $prompt->provider }}</span>
                </p>
            </div>

            <div class="flex flex-col text-center w-full mb-8">
                <h2 class="md:text-2xl text-xl font-medium text-gray-700 mb-4">
                    Selected Movies
                </h2>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-6 w-full">
            @foreach($prompt->movies as $movie)
                <div class="grow">
                    <div class="w-full sm:mb-0 mb-6">
                        <div class="rounded-lg h-80 overflow-hidden mb-4">
                            {{-- TODO: ask the AI the change this image tag and allow fiting a vertical image in the horizontal space --}}
                            <img alt="cover" class="w-full h-auto object-cover object-center rounded" src="{{ $movie->getThumbnail() }}">
                        </div>

                        <h1 class="text-gray-900 md:text-2xl text-xl title-font font-medium mb-9">
                            <a class="inline-flex items-center gap-1 underline" href="{{ $movie->url }}" target="_blank">
                                {{ $movie->title }} ({{ $movie->year }})
                            </a>
                        </h1>

                        @if(! blank($movie->used_for))
                            <h1 class="text-gray-800 text-lg title-font font-medium mt-2">
                                Used For
                            </h1>
                            <p class="leading-relaxed mb-5">
                                {{ $movie->used_for }}
                            </p>
                        @endif

                        <p class="text-base leading-relaxed mb-4">
                            {{ $movie->overview }}
                        </p>

                    @if(! blank($movie->genres))
                        <p class="leading-relaxed mb-4">
                            {{ implode(', ', $movie->genres) }}
                        </p>
                    @endif

                    </div>
                </div>
            @endforeach
            </div>

            <div class="pt-10">
            @if(! blank($prompt->modifiers))
                <x-prompt-modifiers-view :modifiers="$prompt->modifiers" />
            @endif
            </div>
        </div>
    </section>
</div>
