<?php

declare(strict_types=1);

namespace App\Repositories\Prompters\Dtos;

use App\Repositories\Prompters\Dtos\Base\BasePromptItem;
use Illuminate\Support\Collection;

final class MovieMashupPromptItem extends BasePromptItem
{
    /**
     * @param  Collection<MovieMashupItem>  $movies
     */
    public function __construct(
        public int $modelId,
        public string $header,
        public string $subHeader,
        public string $content,
        public string $provider,
        public Collection $movies,
        public string $view = '',
        public ?ModifierPromptItem $modifiers = null,
    ) {
        parent::__construct($view);
    }

    public function toMarkdown(): string
    {
        $movies = str('### Selected Movies')
            ->append(PHP_EOL.PHP_EOL);

        $this->movies->each(function (MovieMashupItem $movie) use (&$movies) {
            $movies = $movies->append($movie->toMarkdown());
        });

        return str("# $this->header")
            ->append(PHP_EOL.PHP_EOL)
            ->append("## $this->subHeader")
            ->append(PHP_EOL.PHP_EOL)
            ->append($this->content)
            ->append(PHP_EOL.PHP_EOL)
            ->append("<small>Generated by AI using: $this->provider</small>")
            ->append(PHP_EOL.PHP_EOL)
            ->append($movies->trim()->toString())
            ->trim()
            ->append(PHP_EOL.PHP_EOL)
            ->append($this->modifiers?->toMarkdown())
            ->trim()
            ->append(PHP_EOL)
            ->toString();
    }
}
